version: "3.8"
services:
  db:
    image: mysql:latest
    container_name: test_alexej_krawez_todo_db
    volumes:
      - ./src/test/resources/1_CREATE_USERS_TABLE.sql:/docker-entrypoint-initdb.d/1_CREATE_USERS_TABLE.sql
      - ./src/test/resources/2_CREATE_NOTES_TABLE.sql:/docker-entrypoint-initdb.d/2_CREATE_NOTES_TABLE.sql
      - ./src/test/resources/3_FILL_DB.sql:/docker-entrypoint-initdb.d/3_FILL_DB.sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: test_alexej_krawez_todo_db
      MYSQL_USER: deus
      MYSQL_PASSWORD: exmachina
    ports:
      - "3306:3306"

  tests:
    depends_on:
      - db
    image: maven:3
    stop_signal: SIGKILL
    stdin_open: true
    tty: true
    working_dir: $PWD
    volumes:
      - $PWD:$PWD
      - /var/run/docker.sock:/var/run/docker.sock
      # Maven cache (optional)
      - ~/.m2:/root/.m2
    command: mvn test


    #  tomcat:
    #    depends_on:
    #      - db
    #    image: tomcat:9.0.70-jdk8-corretto
    #    volumes:
    #      - ./target/task03.war:/usr/local/tomcat/webapps/task03.war
    #    ports:
    #      - '8080:8080'
    #    environment:
    #      MYSQL_ROOT_PASSWORD: DbLocalRootPassword
    #      MYSQL_DATABASE: test_alexej_krawez_todo_db
    #      MYSQL_USER: deus
    #      MYSQL_PASSWORD: exmachina